---
- name: Install PostgreSQL and required packages '{{ inventory_hostname }}'
  become: true
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  loop:
    - percona-postgresql-{{ postgres_version }}
    - gnupg2
    - lsb-release
    - curl

- name: Create PostgreSQL Data Directory
  file:
    path: "{{ postgres_data_dir }}/{{ postgres_version }}/main/"
    state: directory
    owner: postgres
    group: postgres
  become: true

- name: Copying postgresql.conf file
  template:
    src: postgresql.conf.j2
    dest: "{{ postgres_data_dir }}/{{ postgres_version }}/main/postgresql.conf"
  become: true

- name: Configure pg_hba.conf
  copy:
    dest: "{{ postgres_data_dir }}/{{ postgres_version }}/main/pg_hba.conf"
    content: |
          host    all             all             0.0.0.0/0            md5
  become: true


- name: Disable postgres service
  ansible.builtin.systemd:
    name: postgresql
    enabled: no
    state: stopped
  become: true

- name: Remove postgres data directory
  ansible.builtin.shell: |
        sudo rm -fr /var/lib/postgresql/{{ postgres_version }}/main
  become: true

